# Generated by Django 3.2.8 on 2021-10-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_transaction_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='jsontext',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
